/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "iiitb_counter.v:1" *)
module bcd(RN, CK, Qz, Qu, Q);
  (* src = "iiitb_counter.v:8" *)
  wire [3:0] _00_;
  (* src = "iiitb_counter.v:8" *)
  wire [3:0] _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "iiitb_counter.v:2" *)
  input CK;
  (* src = "iiitb_counter.v:5" *)
  output [7:0] Q;
  (* src = "iiitb_counter.v:4" *)
  output [3:0] Qu;
  (* src = "iiitb_counter.v:6" *)
  wire [3:0] Qu1;
  (* src = "iiitb_counter.v:3" *)
  output [3:0] Qz;
  (* src = "iiitb_counter.v:6" *)
  wire [3:0] Qz1;
  (* src = "iiitb_counter.v:2" *)
  input RN;
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(Qu1[0]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__nand2_1 _16_ (
    .A(Qu1[3]),
    .B(Qu1[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor4bb_1 _17_ (
    .A(Qu1[2]),
    .B(Qu1[1]),
    .C_N(Qu1[0]),
    .D_N(Qu1[3]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(Qu1[0]),
    .B(Qu1[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2_1 _19_ (
    .A(_03_),
    .B(_04_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _20_ (
    .A1(Qu1[0]),
    .A2(Qu1[1]),
    .B1(Qu1[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__and3_1 _21_ (
    .A(Qu1[2]),
    .B(Qu1[0]),
    .C(Qu1[1]),
    .X(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _22_ (
    .A(_05_),
    .B(_06_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__o22a_1 _23_ (
    .A1(Qu1[3]),
    .A2(_06_),
    .B1(_00_[2]),
    .B2(_02_),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(Qz1[1]),
    .B(Qz1[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(Qz1[3]),
    .B(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_1 _26_ (
    .A1(_03_),
    .A2(_08_),
    .B1(Qz1[0]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(Qz1[0]),
    .A2(_03_),
    .B1(_09_),
    .Y(_01_[0])
  );
  sky130_fd_sc_hd__nand3_1 _28_ (
    .A(Qz1[0]),
    .B(Qz1[1]),
    .C(_03_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a21o_1 _29_ (
    .A1(Qz1[0]),
    .A2(_03_),
    .B1(Qz1[1]),
    .X(_11_)
  );
  sky130_fd_sc_hd__and3_1 _30_ (
    .A(_08_),
    .B(_10_),
    .C(_11_),
    .X(_01_[1])
  );
  sky130_fd_sc_hd__nand4_1 _31_ (
    .A(Qz1[0]),
    .B(Qz1[1]),
    .C(Qz1[2]),
    .D(_03_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(Qz1[2]),
    .B(_10_),
    .Y(_01_[2])
  );
  sky130_fd_sc_hd__nand2b_1 _33_ (
    .A_N(Qz1[3]),
    .B(Qz1[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__xor2_1 _34_ (
    .A(Qz1[3]),
    .B(_12_),
    .X(_14_)
  );
  sky130_fd_sc_hd__a31oi_1 _35_ (
    .A1(_03_),
    .A2(_07_),
    .A3(_13_),
    .B1(_14_),
    .Y(_01_[3])
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(CK),
    .D(_00_[0]),
    .Q(Qu1[0]),
    .RESET_B(RN)
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(CK),
    .D(_00_[1]),
    .Q(Qu1[1]),
    .RESET_B(RN)
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(CK),
    .D(_00_[2]),
    .Q(Qu1[2]),
    .RESET_B(RN)
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(CK),
    .D(_00_[3]),
    .Q(Qu1[3]),
    .RESET_B(RN)
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(CK),
    .D(_01_[0]),
    .Q(Qz1[0]),
    .RESET_B(RN)
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _41_ (
    .CLK(CK),
    .D(_01_[1]),
    .Q(Qz1[1]),
    .RESET_B(RN)
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(CK),
    .D(_01_[2]),
    .Q(Qz1[2]),
    .RESET_B(RN)
  );
  (* src = "iiitb_counter.v:8" *)
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(CK),
    .D(_01_[3]),
    .Q(Qz1[3]),
    .RESET_B(RN)
  );
  assign Q = { Qz1, Qu1 };
  assign Qu = Qu1;
  assign Qz = Qz1;
endmodule
